FROM openjdk:alpine
COPY . /tmp
WORKDIR /tmp
RUN ./gradlew clean build -x test \
    && mkdir -p /usr/src/app \
    && cp build/libs/reactivespringkotlin-0.0.1-SNAPSHOT.jar /usr/src/app/app.jar \
    && rm -rf /tmp \
WORKDIR /usr/src/app/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "-Djava.security.egd=file:/dev/./urandom -Xmx256m", "/usr/src/app/app.jar"]